### ISSUE TITLE
Document expected usage of `default` characteristic of scenarios, especially in use with `clone()`

### ISSUE THREAD

**Issue by gidden** [iiasa/ixmp#101]
Per our discussion in #97, it would be useful to have a documentation page that covers aspects of how versioning is done on model/scenario data. There are two main topics I see that could be covered at the moment.

First is the application of the `default` characteristic. How is this updated? What happens if there is no default version? How does this interact with `clone()`?

Second is the possible results from `clone()` with various arguments. E.g., what if I only give `model`, only `scenario` or both? What if model and scenario are the same as the copy-ee?

This could be pretty simple page enumerating all possible procedures with expected outcomes.

**Comment by khaeru** [comment]
Some of this also cropped up in #108, but wasn't fully addressed there.
