### ISSUE TITLE
Clone across platforms (database instances) not operational

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#109]
The current implementation of `Scenario.clone()` does not actually save the scenario to another database instance, only the Python-class internal platform argument is changed.

**Comment by khaeru** [comment]
I've just run into this. @zikolach does this require anything special to be changed/added in the Java code? If not, I can take a stab at it.

**Comment by zikolach** [comment]
@khaeru feel free to contribute. I wouldn't exclude the case that something doesn't work as expected on Java side as well. There are some tests on both sides (java and python) which seem to work. And also latest ixmp.jar might have this indirectly touched (e.g. in commit a782e2edffeaa6fb4bbb7cbe2fbcd0c79d06e0cd)

**Comment by zikolach** [comment]
Related fix https://github.com/iiasa/ixmp_source/pull/141/commits/d5229563430b64a16d005dc477a09628f0591a12 was merged as part of PR iiasa/ixmp_source#141

**Comment by danielhuppmann** [comment]
Please look at https://github.com/danielhuppmann/ixmp/commit/15ddb5d763dd58e24d040c28a088c07518bd2f37 which extends the existing (incorrectly passing) integration tests to make them fail - as they should, because the current implementation does not actually clone a `Scenario` across platforms. Instead it only clones the `Scenario` within the same platform and just overwrites the Python-internal `mp` arg.

**Comment by zikolach** [comment]
@danielhuppmann @khaeru there was missing first parameter in clone method (which is needed to cross-db cloning)
