### ISSUE TITLE
test_utils.py pollutes source directory

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#152]
https://github.com/iiasa/ixmp/blob/fb195fda9b5b2fc0f7c8556ad4830dc83af06566/tests/test_utils.py#L9-L20

Calling `make_obs()` with 'temp.csv' (a filename with no directory component) causes the file to be created in the directory where tests are invoked. Instead, the [pytest `tmp_path` fixture](https://docs.pytest.org/en/latest/tmpdir.html#the-tmp-path-fixture) should be used.

**Comment by khaeru** [comment]
@GamzeUnlu95 can you please also tackle this issue for us? The change is very similar to the one you made in #205. Thanks!

**Comment by GamzeUnlu95** [comment]
In my case, I did not have this issue. When I  invoked this test, the 'test.csv' file was not created in the directory that the tests are invoked. However, I added a tmp_path fixture in PR [#223. ](https://github.com/iiasa/ixmp/pull/223).
