### ISSUE TITLE
Script installation error on Windows when executing install.bat

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/ixmp#159]
If Anaconda has been installed as a system-wide application as opposed to a user-specific application in Windows, then installing ixmp (and message_ix) via `install.bat` results in an error related to permissions.  The issue arises when installing scripts. See example below:

`Installing import-timeseries-script.py script to C:\ProgramData\Anaconda3\Scripts
error: [WinError 5] Access is denied: 'C:\\ProgramData\\Anaconda3\\Scripts\\import-timeseries-script.py'`

In order to circumvent this behavior, the user must execute the install.bat with admin privelages.

**Comment by OFR-IIASA** [comment]
To be more precise on the work-around. `install.bat` cannot be executed as an admin.  This results in another error (see below). It is necessary to open a command line window as an admin and then execute `install.bat`.

`C:\WINDOWS\system32>rem Install ixmp and rixmp from source on Windows
C:\WINDOWS\system32>rem
C:\WINDOWS\system32>rem TODO if this script is to be kept/supported, describe it in the docs.
python: can't open file 'setup.py': [Errno 2] No such file or directory`

**Comment by khaeru** [comment]
See [this comment](https://github.com/iiasa/message_ix/issues/215#issuecomment-505779401) on the parallel issue iiasa/message_ix#215 for a proposed solution.

**Comment by khaeru** [comment]
Because of limitations like this, the install.bat script was removed, and standard Python/R installation methods are now recommended/supported for ixmp.
