### ISSUE TITLE
F-strings are only compatible with Python ≥3.6, not 3.5

### ISSUE THREAD

**Issue by zikolach** [iiasa/ixmp#168]
There is a line `result.append(f"{indent}'{arg}' (above)")` in `ixmp/reporting/describe.py` which makes `ixmp` compatible with python 3.6+ only, but currently we did not drop support of neither python 2 or python 3.5.

**Comment by khaeru** [comment]
The documentation states that the reporting features are experimental in ixmp 0.2, and only support Python 3.

**Comment by zikolach** [comment]
The issue is that test suite fails on python 3.5. Is it expected?

**Comment by khaeru** [comment]
Just a thought: we should check out dependencies and see what is the highest minimum Python version.

**Comment by zikolach** [comment]
Yeah, recently I had hard time figuring out that [one of the dependencies](https://github.com/openclimatedata/openscm/blob/master/setup.py#L125) was not working because of not having python 3.7. So pip had it installed, just `import` didn't work.

**Comment by khaeru** [comment]
For reference, [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) from numpy (one of our dependencies) has only Python 3.6+ as of yesterday.

**Comment by khaeru** [comment]
> Just a thought: we should check out dependencies and see what is the highest minimum Python version.

As of #263, we require [pandas 1.0 which in turn requires Python 3.6.1](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#increased-minimum-version-for-python) (see also pandas-dev/pandas#29212).
