### ISSUE TITLE
errors when trying R installation

### ISSUE THREAD

**Issue by gidden** [iiasa/ixmp#169]
I got the following errors when trying our R installation instructions (which does not mention the expectation of such errors):

```
$ R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘rixmp’:
* checking DESCRIPTION meta-information ... OK
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted
```

(fixed by installing `knitr`)

then

```
$ R CMD INSTALL *.tar.gz
* installing to library ‘/home/gidden/.local/R/library’
ERROR: dependency ‘reticulate’ is not available for package ‘rixmp’
* removing ‘/home/gidden/.local/R/library/rixmp’
```

(fixed by installing `reticulate`)

**Comment by gidden** [comment]
cc @adrivinca and/or @khaeru not sure if these are expected or not. Quite easy to fix, but maybe worth adding a note in the docs? Also, the docs say that `reticulate` will be installed for you in the second step, but I did not find that to be the case.

**Comment by khaeru** [comment]
@gidden, thanks for the check. Indeed, `R CMD install` does not fetch or install dependencies from CRAN. (If we provided a CRAN package (we don't), then fetching and installing rixmp from CRAN would also bring these in.)

I think the most robust fix would be adding `Rscript -e "install.packages(c('knitr', 'reticulate'))"` to the instructions.

**Comment by gidden** [comment]
+1
