### ISSUE TITLE
Use sparse xarray for reporting.Quantity

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#191]
[xarray 0.13](http://xarray.pydata.org/en/stable/whats-new.html#v0-13-0-17-sep-2019) includes support for converting pd.DataFrame to a [pydata/sparse](https://sparse.pydata.org) data structure.
This should mostly obviate the need for the custom AttrSeries class.
A PR should be opened to make the change, test performance, and make any necessary adjustments.

Resources:
- Pint's technical commentary on container class hierarchy: https://pint.readthedocs.io/en/0.11/numpy.html#Technical-Commentary
- [AmphoraInc/xarray_mongodb](https://github.com/AmphoraInc/xarray_mongodb), which integrates xarray, sparse, and pint, for reference (thanks @gidden).

**Comment by khaeru** [comment]
#317 / iiasa/message_ix#372 partly addresses this issue; however, we still await a release of xarray >0.15.1 (see pydata/xarray#4031) to fix pydata/xarray#4019, which causes incorrect computation results in sparse-backed xarray.DataArray.

**Comment by khaeru** [comment]
> we still await a release of xarray >0.15.1 (see [pydata/xarray#4031](https://github.com/pydata/xarray/issues/4031)) to fix [pydata/xarray#4019](https://github.com/pydata/xarray/issues/4019)

This is now fixed & released.

**Comment by francescolovat** [comment]
Based on your previous comment, @khaeru, can we close this issue?

**Comment by khaeru** [comment]
> can we close this issue?

In short, no. That was an issue which blocked this one.

The block is now cleared, but we would still need to have a PR to implement the changes described here.

**Comment by khaeru** [comment]
This is to be continued at khaeru/genno#23.
