### ISSUE TITLE
"FlywayException: Validate failed" is cryptic

### ISSUE THREAD

**Issue by jkikstra** [iiasa/ixmp#194]
FYI @zikolach 

After having run MESSAGE_ix installed through Anaconda on my machine, I uninstalled it again, deleted the folders in `site-packages` and then installed `ixmp` and `message_ix` through the source code. 

This resulted in the following error when running `mp = ixmp.Platform(dbtype='HSQLDB')`:
```
---------------------------------------------------------------------------
org.flywaydb.core.api.FlywayException     Traceback (most recent call last)
<ipython-input-2-8838b5a9d05d> in <module>
----> 1 mp = ixmp.Platform(dbtype='HSQLDB')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\ixmp\core.py in __init__(self, dbprops, dbtype, jvmargs)
    106                 logger().info("launching ixmp.Platform with local {} database "
    107                               "at '{}'".format(dbtype, dbprops))
--> 108                 self._jobj = java.ixmp.Platform("Python", str(dbprops), dbtype)
    109             else:
    110                 raise ValueError('Unknown dbtype: {}'.format(dbtype))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\jpype\_jobject.py in __init__(self, *args)
     93             object.__setattr__(self, '__javavalue__', args[0])
     94         elif not hasattr(self, '__javavalue__'):
---> 95             jv = self.__class__.__javaclass__.newInstance(*args)
     96             object.__setattr__(self, '__javavalue__', jv)
     97         super(JObject, self).__init__()

org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.21
```

@khaeru pointed out that this is caused by the source code run expecting a new schema version of the database that is similar to the Java version that's being run, but finds that the older schema is present as the older database is still on the local computer.

Deleting all files (the local database) stored in `~/.local/share/ixmp/localdb/default.*` resolves the issue.

**Comment by zikolach** [comment]
> @khaeru pointed out that this is caused by the source code run expecting a new schema version of the database that is similar to the Java version that's being run, but finds that the older schema is present as the older database is still on the local computer.

It is quite hard to understand from explanation ;) The underlying issue is that installed package has no migration file with version already applied by another version to local database. Which means it is either older version (which is not possible as master is latest) or there is some mess up with pip cache. Can you try `pip install --no-cache-dir .` or something similar? If it won't help can you please check md5 of ixmp.jar file in your `site-packages/ixmp` folder and the one on Github?

**Comment by khaeru** [comment]
As I understand, @jkikstra did this:
1. Installed ixmp from conda, i.e. release 0.2.
2. Used it; so a local database was created.
3. Re-installed ixmp from source.
4. Used it again.

This produced the exception above.

The main issue is that the exception message is cryptic and doesn't offer the user a reasonable chance of identifying a solution. An easy fix will be to catch and re-raise the exception (in Python) with a message like: “The schema of database [path to database] does not match the schema of this version of ixmp. To resolve, either install the version of ixmp used to create the database, or delete it and retry.”

- In the longer run, if the schema could be updated automatically in ixmp_source, that would help.
- #182 should relocate any catch/re-raise code to JDBCBackend.
