### ISSUE TITLE
Clarify R installation

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#196]
I sat with @guofei2016 today who was trying to reinstall both ixmp and message_ix for use from R on Windows. We encountered the following difficulties:

- His R install (RStudio) had not added the R and Rscript executables to his PATH.
- Consequently, install.bat failed, and rixmp was not installed.
- When we tried to execute the relevant lines from the Command Prompt, the line ``Rscript -e "install.packages(c('knitr', 'reticulate'))"`` failed because no CRAN mirror was specified. (We succeeded by prepending the following line from ci/appveyor-install.R: ``options(repos=c('https://cloud.r-project.org'), pkgType='win.binary')``.)

Through this, I observed that install.bat (1) hardcodes a version number, and (2) when run from Windows Explorer, closes immediately on failure, so it is not possible for the user to see, understand, and try to resolve any problems.

## Fixes

- Delete install.bat.
- Update the R install docs to clearly & simply state:
  - The R installation requires installing Python ixmp from source.
  - User should ensure & test that Rscript and R are on their PATH.
  - The Windows, macOS, and Linux installs require the same sequence of commands, which the user should enter directly in the terminal. (Although this is more steps than the current instruction to use install.bat, it at least offers a reasonable chance for debugging.)
- Remove the instruction to install Rtools. @adrivinca—do you recall what this was for? Is it still necessary? @guofei2016 seems to think it is not.

**Comment by adrivinca** [comment]
I should go back and check some of these problems, from what I can recall now:

- the R path need to be manually saved in the environment paths, it has never been automatic
- Rtools were needed when leading internally built packages. But not sure if it is still a requirement for newer versions of R and other OS

I remember I write updated documentation for the new release, which it doesn't seem to be online. I will try to find it and update/correct

**Comment by khaeru** [comment]
Linked issues/PRs:
- iiasa/message_ix#377 can provide an example here.
- Can be handled at the same time as #344.
