### ISSUE TITLE
Add unit tests for R API

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#20]
Now that we have implemented the `rixmp` package (see PR #19), we should add unit tests to make sure that future changes do not cause problems with existing features.

**Comment by khaeru** [comment]
This was discussed at today's (2019-04-10) MESSAGE meeting; see the OneNote notebook for minutes.

We will use this issue to collect a list of things that should be tested. The tests will be developed for the release after 0.2 (either 0.3 or 1.0).

**Comment by khaeru** [comment]
Closed via #135, which will be in 0.2 after all. Developers can now write tests using the [testthat](https://testthat.r-lib.org) package in files like `rixmp/tests/testthat/test_*.R` to check specific behaviour of the reticulate-based R interface to `ixmp`.
