### ISSUE TITLE
.gms files on network drive not recognized

### ISSUE THREAD

**Issue by Jihoon** [iiasa/ixmp#203]
Path setups for gams files from `gams.py` do not correctly bring in files on network drives.

The absolute paths from Path.resolve() cannot be recognized from GAMS for some reason. And it complains as follows:

`'\\hdrive\home$\u045\min\mydocuments\MESSAGE\message_ix\message_ix\model'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.`

Removing `.resolve()` seems to resolve the issue.

**Comment by khaeru** [comment]
Thanks @Jihoon for this issue report.

> Removing `.resolve()` seems to resolve the issue.

[`pathlib.Path.resolve()` is used in several places](https://github.com/iiasa/ixmp/search?q=resolve&unscoped_q=resolve). Can you specify which one(s) you removed to fix this issue on your system?

**Comment by Jihoon** [comment]
There are three uses I find in the `main` definition. I removed all three.

**Comment by khaeru** [comment]
@Jihoon if that has solved the problem for you, can you please create a PR so that it can be resolved for everyone?

**Comment by Jihoon** [comment]
> @Jihoon if that has solved the problem for you, can you please create a PR so that it can be resolved for everyone?

Thanks. Done #230.
