### ISSUE TITLE
add_par() changes the input data frame

### ISSUE THREAD

**Issue by Jihoon** [iiasa/ixmp#210]
After a certain recent commit, calling `sc.add_par('par', df)` modifies the `df` by attaching `key` and `comment` columns at the end.

**Comment by khaeru** [comment]
Nice catch @Jihoon.

The fix will be here: https://github.com/iiasa/ixmp/blob/b155643f6bb853a3213e0410d8e74ada4bf7bfe2/ixmp/core.py#L991-L998 —specifically at line 996, a .copy should be used.
