### ISSUE TITLE
ixmp should set the same datatypes for both var and par 

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/ixmp#218]
when retrieving data, the year values for a parameter are returned as integers, whereas for variables these are returned as strings.

A quick test:

model = <model name of a scenario with a solution>
scen_name = <name of scenario with solution>
scen = message_ix.Scenario(mp, model, scen_name)
print(scen.par('relation_activity').year_act.unique().tolist())
print(scen.var('ACT').year_act.unique().tolist())

using this on a scenario results in:
print(scen.par('relation_activity').year_act.unique().tolist())
[1990, 1995, 2000, 2005, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2110]
print(scen.var('ACT').year_act.unique().tolist())
['1990', '1995', '2000', '2005', '2010', '2020', '2030', '2040', '2050', '2060', '2070', '2080', '2090', '2100', '2110', '1950', '1955', '1960', '1965', '1970', '1975', '1980', '1985']

I would guess that the issue is a result of:
ixmp.backend.jdbc.item_get_elements()

**Comment by khaeru** [comment]
This is the same as iiasa/message_ix#268.

**Comment by khaeru** [comment]
Closing this as “wontfix” in *ixmp*; the fix is in iiasa/message_ix#269.
