### ISSUE TITLE
Solve error under Windows 10

### ISSUE THREAD

**Issue by tzipperle** [iiasa/ixmp#24]
I get the following error when I try to solve the model with: `scen.solve(model='MESSAGE):`

> subprocess.CalledProcessError: Command 'gams "MESSAGE.gms" --in="MESSAGE_in.gdx" --out="MESSAGE_out.gdx" LogOption=4' returned non-zero exit status 6.

`model_file` in ixmp/core is gives the following string `MESSAGE.gms`. In a former version `model` was a path to `MESSAGE_run.gms` .

Current version:
`model = os.path.join(ix.default_paths.MODEL_DIR, '{}_run.gms'.format(model))`

Older version:
`model_file= model_file or config.model_file.format(model=model)`  

I am not sure if I made a error during the installation process or this is a general error.

**Comment by danielhuppmann** [comment]
hi @tzipperle , due to the migration, we separated all MESSAGE-specific parts from the generic `ixmp` aspects. To use it as before, you just have to load the package `message_ix` at the beginning of any Python script - this will tell the `ixmp` package that whenever the model is `MESSAGE` or `MESSAGE-MACRO`, it should use the default MESSAGE GAMS file names and paths.

Please let me know whether this solves your problem

**Comment by tzipperle** [comment]
Only the import is not enough. 

```
import message_ix
model = model=message_ix.model_file.format(model='MESSAGE').replace('.gms', '')
scen.solve(model=model)
```

With the upper workaround it works...

**Comment by danielhuppmann** [comment]
when you run `install.bat` in your `message_ix` (`message_ix_dev`) clone, do all unit tests pass? In particular the one on the tutorials?

**Comment by tzipperle** [comment]
I have uninstalled `message_ix` and reinstalled. Now it works fine with the import statement.

But when I run the `install.bat` under `message_ix`, then the unit test doesn't starts. Only when I call it under `message_ix/ixmp` - all tests pass.

**Comment by danielhuppmann** [comment]
@OFR-IIASA , does this also happen on your Windows 10 PC? Do the unit tests run when you double-click `install.bat` in the `message_ix` folder?

**Comment by OFR-IIASA** [comment]
@danielhuppmann , I havent encountered this issue.  When I execute install.bat two sets of tests are executed.

**Comment by danielhuppmann** [comment]
@tzipperle , can you post a screenshot of the command prompt when executing the top-level `install.bat`?

**Comment by danielhuppmann** [comment]
thanks @OFR-IIASA !

**Comment by danielhuppmann** [comment]
thanks @tzipperle for identifying and solving this issue!
