### ISSUE TITLE
ERROR AttributeError: 'types.SimpleNamespace' object has no attribute 'Properties'

### ISSUE THREAD

**Issue by DIUANA** [iiasa/ixmp#258]
When I install IXMP from source and run test.py. I am getting this error: `AttributeError: 'types.SimpleNamespace' object has no attribute 'Properties'`  related to the file ixmp\backend\jdbc.py
 If I ignore this error in the test and install message ix anyway I get this error when I run : `mp = ixmp.Platform(dbtype='HSQLDB')`

I have installed from source many times before and I have never gotten this error.
I believe I have added all required paths to the environment variables:

C:\Program Files\Java\jdk1.8.0_231\jre\bin\server
C:\Program Files\Java\jdk1.8.0_231\jre\bin
D:\ProgramFiles\GAMS\win64\24.7
D:\ProgramFiles\Anaconda3
D:\ProgramFiles\Anaconda3\Scripts
D:\ProgramFiles\Anaconda3\Library\bin

What might be causing this issue?

**Comment by DIUANA** [comment]
I updated my jpype package by reinstalling it via conda install -c conda-forge jpype1

Now it is working.

**Comment by khaeru** [comment]
> Now it is working.

Great to hear!

If the issue no longer exists, you can hit the "Close issue" button below.
