### ISSUE TITLE
Resolve issues with JPype1 0.7.2, 0.7.3

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#279]
In #278, iiasa/message_ix#313, and iiasa/message_data#106, we excluded JPype1 version 0.7.2 from CI builds because it causes segfaults. The builds succeed with version 0.7.1.

We need to investigate and ensure that ixmp (and thus the whole MESSAGEix stack) works with the latest JPype1 at the time of the next release. Otherwise, users installing ixmp etc. from PyPI/conda-forge will run into this problem.

Notes here follow for investigation:
- jpype-project/jpype#605 (issue) and jpype-project/jpype#611 (PR fix) also concern exception handling in JPype; these are ~recent and unreleased~ now released in JPype 0.7.3.
- JPype 0.7.3 caused different test issues in both ixmp and message_ix: see below at https://github.com/iiasa/ixmp/issues/279#issuecomment-619439059. The **temporary** mitigation is to exclude *both* JPype 0.7.2 and 0.7.3.

**Comment by khaeru** [comment]
@zikolach reports:
- Install JPype1 `master` branch from source (i.e. built on local machine) using pip.
- `pytest -x ixmp/tests > test.log` → produces [test.log](https://github.com/iiasa/ixmp/files/4324767/test.log)
```
----------------------------- Captured stderr call -----------------------------
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0x0</M>
<M>unknown : Inner Python: unknown error</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 34</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0x0</M>
<M>unknown : Inner Python: unknown error</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 34</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0x0</M>
<M>unknown : Inner Python: unknown error</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 34</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0x0</M>
<M>unknown : Inner Python: unknown error</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 34</M>
```

**Comment by khaeru** [comment]
Okay, I'm able to recreate this. On my system (Ubuntu 19.10), I had to `apt install ant openjdk-8-jdk` in order to `pip install --user --editable git+https://github.com/jpype-project/jpype#egg=jpype1`.

**Comment by khaeru** [comment]
File jpype-project/jpype#630.

**Comment by khaeru** [comment]
The JPype devs developed a fix; see https://github.com/jpype-project/jpype/pull/633#issuecomment-600492857.

**Comment by khaeru** [comment]
The fix was merged and the issue has been closed. Now we wait for a release >0.7.2.

**Comment by khaeru** [comment]
For the record: I updated the message_ix `2.0.x` maintenance branch using commit 8108eb8 from message_ix `master`:
```
$ git checkout 2.0.x
$ git cherry-pick 8108eb8
```

This lets the nightly/CRON CI for that branch continue to pass. Once this issue is closed, it can be reverted.

**Comment by khaeru** [comment]
JPype 0.7.3 was just released: https://github.com/jpype-project/jpype/releases/tag/v0.7.3

Since we've only excluded 0.7.2 (`!= 0.7.2`), then 0.7.3 should get pulled into the next CI runs, and we will find out whether it resolves these issues.

**Comment by khaeru** [comment]
For **message_ix** (not ixmp), Travis jobs that use JPype 0.7.3 such as 1729.1 are failing [with messages like](https://travis-ci.com/github/iiasa/message_ix/jobs/323308726#L1457):
```
>           self.jindex[ts].readSolutionFromGDX(*args)
E           TypeError: Ambiguous overloads found for at.ac.iiasa.ixmp.objects.MsgScenario.readSolutionFromGDX(str,str,str,java.util.LinkedList,java.util.LinkedList,bool) between:
E           	public void at.ac.iiasa.ixmp.objects.MsgScenario.readSolutionFromGDX(java.lang.String,java.lang.String,java.lang.String,java.util.List,java.util.List,boolean) throws at.ac.iiasa.ixmp.exceptions.IxException
E           	public void at.ac.iiasa.ixmp.objects.Scenario.readSolutionFromGDX(java.lang.String,java.lang.String,java.lang.String,java.util.LinkedList,java.util.LinkedList,boolean) throws at.ac.iiasa.ixmp.exceptions.IxException

../../../miniconda/envs/testing/lib/python3.8/site-packages/ixmp/backend/jdbc.py:346: TypeError
```

FYI @zikolach.

I just checked and the signature of `at…Scenario` on `master` seems not to use LinkedList since recently (iiasa/ixmp_source#285): https://github.com/iiasa/ixmp_source/blob/master/src/main/java/at/ac/iiasa/ixmp/objects/Scenario.java#L1374 —so I guess this is included on some .jar file update on some branch? Would that resolve the issue? Do we need to change LinkedList to List in the Python JDBCBackend code?

This seems to be the common cause of a number of different test failures.

----
For **ixmp** *per se*, Travis jobs that use JPype 0.7.3, such as 1398.1, appear to be failing [with messages like](https://travis-ci.com/github/iiasa/ixmp/jobs/323368163#L2566-L2570).

```
────────────────────────────────────────────────────────────────────────────────

test_core.R:66: failure: the canning problem can be solved

scen$var("z")$lvl not equal to 153.675.

'current' is not an environment

────────────────────────────────────────────────────────────────────────────────
```

Only the two R-related tests fail. We discussed this with @adrivinca in Slack, who said the message wasn't a familiar one.

I am not sure if these R failures 

----

For the moment, I will make quick changes to:
- exclude both JPype 0.7.3 **and** 0.7.2 from CI and requirements on `master` and `2.0.x`—this should allow us to see if the R tests are related—and
- do the same for message_ix.

But we need to diagnose and resolve these issues.

**Comment by zikolach** [comment]
> Do we need to change LinkedList to List in the Python JDBCBackend code?

I don't think so. LinkedList is an implementation of List interface. In very rare cases a specific implementation has to be a part of contract (method signature). Passing an instance of LinkedList to the method expecting List as an argument is perfectly fine.

> E           	public void at.ac.iiasa.ixmp.objects.Scenario.readSolutionFromGDX(java.lang.String,java.lang.String,java.lang.String,java.util.LinkedList,java.util.LinkedList,boolean) throws at.ac.iiasa.ixmp.exceptions.IxException

Initially changing method signatures was made on 24.10.2018 1bf42ecd1b4d1c95ab0bbd1c4e0f7d789da5e36c (the source change leading to different signatures), on 14.04.2020 eba71d10a031041ac81fa0cc1388225ab5bf803a it was (finally) changed to use List in other places too. It could be that JPype was changed and now can detect signatures difference.

**Comment by khaeru** [comment]
>  It could be that JPype was changed and now can detect signatures difference.

Yes, I am guessing that's it. But I read through the changelog for v0.7.3 (linked above) and there's no reference to it.

> > Do we need to change LinkedList to List in the Python JDBCBackend code?
> 
> I don't think so. […] Passing an instance of LinkedList to the method expecting List as an argument is perfectly fine.

It might be perfectly fine from a Java perspective, but in order for message_ix to work, we have to somehow make JPype choose the right method.

Thinking further:
- List is the interface, LinkedList is an implementation.
- The call is made with LinkedList arguments.
- MsgScenario is the object's class, *but* its overload is not an exact match (matches the List interface, but not the concrete LinkedList class)
- The Scenario method signature is an exact match, *but* it's the parent class.

Perhaps it's the latter two that make JPype see an ambiguity?

> on 14.04.2020 [iiasa/ixmp_source@eba71d1](https://github.com/iiasa/ixmp_source/commit/eba71d10a031041ac81fa0cc1388225ab5bf803a) it was (finally) changed to use List in other places too

Do we know if this code is already in the .jar on ixmp `master`?

**Comment by khaeru** [comment]
- JPype 0.7.5 is released: https://github.com/jpype-project/jpype/releases/tag/v0.7.5
- @ayeletdavidovitch and @aviramohad reported encountering this issue; the suggested fix was to install JPype 0.7.1 specifically.

**Comment by zikolach** [comment]
I just tested ixmp (on mac osx) and message_ix (in Docker container) running with JPype 0.7.5 - for both tests did pass. Also see latest master build on TC.

**Comment by khaeru** [comment]
- #327 bumps the JPype requirement for ixmp to 0.7.5. R tests still fail as described at https://github.com/iiasa/ixmp/issues/279#issuecomment-619439059; r-lib/testthat#1035 was filed to follow-up.
- iiasa/message_ix#351 bumps CI for message_ix to 0.7.5.
