### ISSUE TITLE
Integrate `nodes` from MESSAGE-scheme `Scenario` set and the `timeseries` data

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#28]
At the moment, defining a new element in the set `node` of a MESSAGE-scheme `ixmp.Scenario` does not add an entry to the table `IAMC_NODES`, meaning that one cannot directly use that node in the `add_timeseries()` command.

**Comment by gidden** [comment]
Hey @danielhuppmann, after talking with @tzipperle and @ClaraLuisa, it sounds like this may be needed/useful depending on what happens with the yssp SA modeling. Is this something we could tackle this week?

**Comment by danielhuppmann** [comment]
hi @tzipperle , thanks for the reminder - it's one of the things that are on the to-do list for the release of  MESSAGEix 1.1 together with the next version of ixmp...

**Comment by tzipperle** [comment]
Hey @danielhuppmann , the solution to this issue didn't make it to version 1.1.0, did it?
