### ISSUE TITLE
Export timeseries data has wrong docstring

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#306]
See the docs of the function `Platform.export_timeseries_data` [here](https://github.com/iiasa/ixmp/blob/ea8595120203f666c422fb904609f5b289417f37/ixmp/core.py#L182), which should refer to `subannual` instead of `time`.

Is this an issue only in the docs or also in the code implementation & backend?

**Comment by zikolach** [comment]
Only in docstring (see [here](https://github.com/iiasa/ixmp_source/blob/master/src/main/java/at/ac/iiasa/ixmp/database/DbDAO.java#L5214))

**Comment by khaeru** [comment]
Closed by #307.
