### ISSUE TITLE
problem with init_par if index set is more than 1 character long

### ISSUE THREAD

**Issue by adrivinca** [iiasa/ixmp#35]
it is not possible to initialize a new parameter if the index set is not a single letter set, taking example from the transport tutorial:

> 
> scen.init_set("i")
> scen.add_set("i", ["seattle", "san-diego"])
> scen.init_set("j")
> scen.add_set("j", ["new-york", "chicago", "topeka"])                                                                                                                                 
> scen.init_par("a", idx_sets="i")
> scen.add_par("a", "seattle", 350, "cases")
> scen.add_par("a", "san-diego", 600, "cases")                                                                                                                             
> scen.init_par("b", idx_sets="j")
> b_data = [
>     {'j': "new-york", 'value': 325, 'unit': "cases"},
>     {'j': "chicago",  'value': 300, 'unit': "cases"},
>     {'j': "topeka",   'value': 275, 'unit': "cases"}
> ]
> b = pd.DataFrame(b_data)
> scen.add_par("b", b)

works properly, but when the set is a string with mode than one character it does not.

> scen.init_set("iii")
> scen.add_set("iii", ["seattle", "san-diego"])
> scen.init_set("jjj")
> scen.add_set("jjj", ["new-york", "chicago", "topeka"])   
> scen.set('iii')                                                                                                                               
> scen.init_par("a", idx_sets="iii")
> scen.add_par("a", "seattle", 350, "cases")
> scen.add_par("a", "san-diego", 600, "cases")                                                                                                                            
> scen.init_par("b", idx_sets="jjj")
> b_data = [
>     {'j': "new-york", 'value': 325, 'unit': "cases"},
>     {'j': "chicago",  'value': 300, 'unit': "cases"},
>     {'j': "topeka",   'value': 275, 'unit': "cases"}
> ]
> b = pd.DataFrame(b_data)
> scen.add_par("b", b)

the tutorial with this issue is attached

[py_transport.zip](https://github.com/iiasa/ixmp/files/2044198/py_transport.zip)

**Comment by gidden** [comment]
Thanks @adrivinca. Would you be able to add a PR with a test that fails? We can diagnose from there.

**Comment by danielhuppmann** [comment]
Thanks @adrivinca ! I believe that

`scen.init_par("a", idx_sets="iii")`

interprets `iii` as `[ 'i', 'i', 'i']`. Try  the following:

`scen.init_par("a", idx_sets=["iii"])`.

A better long-term solution would be to to rewrite the function `_getCleanDims()` in `ixmp/core.py` to check if the dimension argument is a string.
