### ISSUE TITLE
Set Platform jvmargs via config.json

### ISSUE THREAD

**Issue by adrivinca** [iiasa/ixmp#408]
I was trying to set the option `"jvmargs": "-Xm12G"` or similar as a permanent setting related to my config.

e.g.

> {
>   "platform": {
>     "default": "local",
>     "local": {
>       "class": "jdbc",
>       "driver": "hsqldb",
>       "path": "C:\\Users\\vinca\\.local\\share\\ixmp\\localdb\\default",
> 	  "jvmargs": "-Xm12G"
>     },

Currently it seems manually adding it to the `config.json` file solves the problem. But it seems the functions of `ixmp.Config` are not supporting the writing or reading of such arguments. 

@khaeru suggested opining the issue as a reminder

**Comment by khaeru** [comment]
Thanks @adrivinca!

This can be addressed in 1 or more ways. Ordered according to degree of effort:
1. Update the documentation to describe this addition.
2. Ensure that this can be set programmatically.
3. Ensure (change code; test; document) that this can be set through the `ixmp platform add` CLI command.
