### ISSUE TITLE
Execute tutorial notebooks during install-and-test in temporary db

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#41]
Currently, when installing and running unit tests, the tutorial notebooks are executed using the local default database. Over time, this db will become clogged by thousands of transport problems. It would be better to use temporary database instead.

This could be achieved by replacing the line 
``     "mp = ix.Platform(dbtype='HSQLDB')"``
in any notebook by:
``     "mp = ix.Platform(dbprops=os.path.expanduser(os.path.join('~', '.local', 'ixmp', 'unittest')), dbtype='HSQLDB')"``.

Where all files starting with `unittest` in `~\.local\ixmp` will be deleted after the last unit test.

Note that changing this in the notebook itself would defeat the purpose...

**Comment by khaeru** [comment]
This was fixed in #130.
