### ISSUE TITLE
Exclude Python version 3.6 in CI

### ISSUE THREAD

**Issue by LauWien** [iiasa/ixmp#428]
With issue https://github.com/actions/virtual-environments/issues/4060 _macOS-latest workflows will use macOS-11_, saying "EOL Python versions were deprecated" and the [end-of-life of Python version 3.6](https://endoflife.date/python) being the 23rd of December 2021, using Python version 3.7 instead of 3.6 might make sense. Possible also in message_ix.

**Comment by khaeru** [comment]
The README for [`actions/setup-python`](https://github.com/actions/setup-python#available-versions-of-python) seems to indicate that earlier versions will continue to be available; they'll just not be pre-installed on the runners. This means the setup-python action will need to download and install 3.6, which might be a little slower. At least, that's my interpretation; we should see if that does work on the macos-11 runners.

In general, the policy is:
- The minimum Python version for ixmp can't be earlier than the minimum Python version of its mandatory dependencies (or their mandatory dependencies).
- When those packages remove support or enforce a minimum version, we also remove support.
- We try our best (within reason) to test the minimum version (per the above 2 points) on CI.
