### ISSUE TITLE
Address type hint errors in danzig.py

### ISSUE THREAD

**Issue by LauWien** [iiasa/ixmp#429]
Possible due to the new [release](https://pypi.org/project/mypy/) of mypy on Dec 16th the following errors occurred in the [lint workflow](https://github.com/iiasa/message-ix-models/runs/4691891651?check_suite_focus=true) of `message-ix-models`:
```
ixmp/ixmp/model/dantzig.py:77: error: Argument 2 to "ChainMap" has incompatible type "Mapping[str, object]"; expected "MutableMapping[str, object]"
ixmp/ixmp/model/dantzig.py:77: error: Argument 2 to "ChainMap" has incompatible type "Mapping[str, object]"; expected "MutableMapping[str, Path]"
```
https://github.com/iiasa/ixmp/blob/6f45e7e1b3467796aa9a73291c226119a07ec107/ixmp/model/dantzig.py#L72-L78

Related https://github.com/iiasa/message_ix/issues/538.

**Comment by khaeru** [comment]
> new [release](https://pypi.org/project/mypy/) of mypy on Dec 16th
- It seems like they made 3 releases in quick succession, 0.920, 0.921, and then 0.930: https://pypi.org/project/mypy/#history
- Unfortunately, there appears to be no changelog / what's new page in the mypy code or docs to be a guide to changes between theses releases. I've looked for one a couple times, but couldn't find it.

**Comment by LauWien** [comment]
> * Unfortunately, there appears to be no changelog / what's new page in the mypy code or docs to be a guide to changes between theses releases. I've looked for one a couple times, but couldn't find it.

Yes, I searched for it also and found yesterday this [blogpost](https://mypy-lang.blogspot.com/2021/12/mypy-0930-released.html) e.g. from the latest release 0.930, coming from "News" from the link you posted and then "Read the _blog post_ for details" from the release in June. Not really obvious to find though.. 

I haven't made out so far what was the change which lead to the failing lint, but maybe in this case it should have been a `MutableMapping[str, Any]` all along since we might override `defaults` and look up different types like paths or bools, what do you think? So maybe just a bugfix on their side?
