### ISSUE TITLE
IXMP down

### ISSUE THREAD

**Issue by mjothy** [iiasa/ixmp#487]
The scenario explorer & IXMP service are down.

Requests are returning timeouts (whether through scenario explorer, or http calls to REST endpoints.

Regards,

Mario

**Comment by khaeru** [comment]
This is not the correct repo for filing issues with the Scenario Explorer and associated API. Please re-read [the reply I gave to your other issue](https://github.com/iiasa/ixmp4/issues/3#issuecomment-1617509271) when transferring it to the "ixmp4" repo.

FYI, there was an internet outage at IIASA today, which I guess would cause Scenario Explorer instances to be down. But again, this is not the place to report that.
