### ISSUE TITLE
Advise users to check GAMS log file

### ISSUE THREAD

**Issue by glatterf42** [iiasa/ixmp#511]
https://github.com/iiasa/ixmp/blob/e764f63c38d8327f41c7f9c81318552695de06a2/ixmp/model/gams.py#L195-L224

As suggested by @volker-krey, upon GAMS errors, users should not only check the `.lst` file, but also the `.log` file. I'm not entirely sure what the exact name of these files is, but we can most likely add a line here that checks if such a file exists and points the user to it.

**Comment by khaeru** [comment]
One could duplicate line 199 to create `log_file` path, and then line 220 to print it out, if it exists.

**Comment by glatterf42** [comment]
Are the `.log` files named exactly the same as the `.lst` files except for the ending?

**Comment by khaeru** [comment]
Yes, unless overridden, which we generally do not do. See https://www.gams.com/latest/docs/UG_GamsCall.html#GAMSAOlogfile
