### ISSUE TITLE
Update MESSAGEix scheme defaults in the ixmp core

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#70]
To merge the PRs from the MESSAGEix hackathon, a number of changes are required in the MESSAGE-scheme implementation on the Java side. This should also bump the version number of the MESSAGE scheme settings.

**Comment by danielhuppmann** [comment]
https://github.com/iiasa/message_ix/pull/80

 - add set `shares`
 - add parameter `map_shares_commodity_level(shares,commodity,level,type_tec,type_tec)`
 - add parameter `share_factor_up(shares,node,year_all,time)`
 - add parameter `share_factor_lo(shares,node,year_all,time)`

**Comment by danielhuppmann** [comment]
for better renewables implementation (PR forthcoming)

 - add elements `'unrated'`  and `'firm'` to the set `rating`

**Comment by khaeru** [comment]
@zikolach could you please confirm that the above have been done—and if so, close, perhaps with links to the relevant PRs?

**Comment by khaeru** [comment]
With no reply, and no related issues arising, I am closing this.

In the future, the MESSAGE scheme will be defined in message_ix; not in the Java code underlying ixmp's JDBCBackend. See #254.
