### ISSUE TITLE
Return dataframe of mapping sets, parameters etc. with ordered columns

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp#82]
Currently, calling `Scenario.par()` returns a `pd.DataFrame` with columns in no particular order.

This should be changed to using the order of `Scenario.idx_names() + ['value', 'unit']` (for parameters) and `['lvl', 'mrg']` for variables and equations, respectively.

**Comment by khaeru** [comment]
Just realized this was done as part of setting up the Backend API / JDBCBackend in #182: https://github.com/iiasa/ixmp/blob/59e99e47082a52203e493a5b0b68afc65506e469/ixmp/backend/jdbc.py#L757-L760
