### ISSUE TITLE
Feature: read_sql_query()

### ISSUE THREAD

**Issue by tzipperle** [iiasa/ixmp#90]
Hi @gidden @danielhuppmann,

I have a short question. Is there a possibility to read SQL query into a DataFrame from the Platform? Similar like the pandas command [read_sql_query()](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.read_sql_query.html).

**Comment by danielhuppmann** [comment]
hi @tzipperle - sorry, this won't work because the parameter etc. dataframes are not stored in a relational structure inside the database.
